In [1]:
import numpy as np

In [5]:
vetor = np.array([1,2,3])
print(vetor)
print(type(vetor))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
matriz = np.array([[1,2], [4,6]])
print(matriz)
print(type(matriz))

[[1 2]
 [4 6]]
<class 'numpy.ndarray'>


In [7]:
tensor = np.array([[[1,2], [4,6]], [[3,5], [7,8]]])
print(tensor)
print(type(tensor))

[[[1 2]
  [4 6]]

 [[3 5]
  [7 8]]]
<class 'numpy.ndarray'>


In [12]:
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [13]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


Obtendo dimensão e formato de objetos ndarray

In [17]:
print(vetor.ndim)
print(vetor.shape)
print(matriz.ndim)
print(matriz.shape)
print(tensor.ndim)
print(tensor.shape)

1
(3,)
2
(2, 2)
3
(2, 2, 2)


Obtendo número de elementos

In [18]:
print(vetor.size)
print(matriz.size)
print(tensor.size)

3
4
8


Mudando formato de um array com o reshape

In [19]:
antes = np.array([[1,2,3,4], [5,6,7,8]])
print(antes.shape)

(2, 4)


In [27]:
depois = antes.reshape(2, 2, 2)
print(depois)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Juntando e empilhando arrays vertical (np.vstack) ou horizontalmente (np.hstack)

In [28]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [30]:
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [34]:
h1 = np.array([[1,1,1,1], [1,1,1,1]])
h2 = np.array([[0,0], [0,0]])

In [35]:
np.hstack([h1,h2])

array([[1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0, 0]])

In [38]:
vetor1 = np.array([1, 2, 3, 4, 5, 6, 7])
vetor1.dtype

dtype('int32')

In [40]:
vetor1 = np.array([1, 2, 3, 4, 5, 6, 7,], dtype=np.int64)
vetor1.dtype

dtype('int64')

In [41]:
a = np.array([1.,2.,3.])
a.dtype

dtype('float64')

In [43]:
b = a.astype('int32')
b.dtype

dtype('int32')

In [44]:
np_mat = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(np_mat)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [45]:
py_mat = [[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]
print(py_mat)

[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]


In [50]:
print(f'Python natural: {py_mat[1][3]}')
print(f'Numpy: {np_mat[1, 3]}')

Python natural: 11
Numpy: 11


In [54]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [62]:
np.linspace(0, 50, num=50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [65]:
timeline = np.linspace(0, 3600, num=60)
timeline

array([   0.        ,   61.01694915,  122.03389831,  183.05084746,
        244.06779661,  305.08474576,  366.10169492,  427.11864407,
        488.13559322,  549.15254237,  610.16949153,  671.18644068,
        732.20338983,  793.22033898,  854.23728814,  915.25423729,
        976.27118644, 1037.28813559, 1098.30508475, 1159.3220339 ,
       1220.33898305, 1281.3559322 , 1342.37288136, 1403.38983051,
       1464.40677966, 1525.42372881, 1586.44067797, 1647.45762712,
       1708.47457627, 1769.49152542, 1830.50847458, 1891.52542373,
       1952.54237288, 2013.55932203, 2074.57627119, 2135.59322034,
       2196.61016949, 2257.62711864, 2318.6440678 , 2379.66101695,
       2440.6779661 , 2501.69491525, 2562.71186441, 2623.72881356,
       2684.74576271, 2745.76271186, 2806.77966102, 2867.79661017,
       2928.81355932, 2989.83050847, 3050.84745763, 3111.86440678,
       3172.88135593, 3233.89830508, 3294.91525424, 3355.93220339,
       3416.94915254, 3477.96610169, 3538.98305085, 3600.     