In [1]:
import numpy as np

In [2]:
mat  = np.random.randint(0, 100, (3,3))
print('Mat')
print(mat)
print('-'*32)


Mat
[[72 21 28]
 [27  3 62]
 [45 38 38]]
--------------------------------


In [4]:
%%time
arr = np.arange(0, 10_000)
_ = [x**2 if x%2 == 0 else -100 for x in arr]

CPU times: total: 15.6 ms
Wall time: 6.98 ms


In [5]:
%%time
arr = np.arange(0, 10_000)
_ = np.where(arr%2==0, arr**2, -100)

CPU times: total: 0 ns
Wall time: 3.99 ms


In [6]:
pos = lambda x: x**2 if x%2==0 else -100
var = 1
var2 = 100 if var == 1 else -100
print(var2)
print(var)

100
1


In [7]:
arr = np.random.randint(0, 100, 1_000)

np.where((arr % 2 == 0),
         np.where(arr > 50,
                  -1000,
                  -10
                  ),
         arr
         )


array([-1000,   -10, -1000, -1000,    59, -1000,   -10, -1000,    71,
          43,    43,     9,    41, -1000,    63,    19,   -10,    85,
          55,    31,   -10,   -10, -1000,    17,    49,   -10,    35,
          37,   -10,   -10,    73,   -10, -1000, -1000,    75, -1000,
         -10,    91,    49,    81, -1000,    79,    39, -1000,   -10,
          81,    53,     1,     3,   -10,   -10,   -10,    59,     9,
         -10,    59,    73,    19,    17,    55,   -10,   -10,   -10,
       -1000, -1000, -1000,    85,    13,   -10,    41,   -10,    63,
         -10,    47,   -10,    23,   -10,   -10,    69, -1000,    39,
       -1000,   -10,   -10,    89,    51,    21, -1000,    99,    61,
          73,    93,   -10,    81,   -10,    79,    15,   -10,    75,
          81, -1000, -1000,    25, -1000,     1,     1,     7,    67,
         -10, -1000,   -10, -1000, -1000, -1000, -1000, -1000,   -10,
          63, -1000,    13,   -10,    87,   -10, -1000,   -10,    41,
           1, -1000,

In [8]:
arr = np.array([4, 6, 2, 8])
arr2 = np.array([2, 3, 1, 4])

In [9]:
print(arr + arr2)

# Em pyton ppuro seria
[ele1 + ele2 for ele1, ele2 in zip(arr, arr2)]

[ 6  9  3 12]


[6, 9, 3, 12]

In [10]:
print(arr - arr2)

# Em pyton ppuro seria
[ele1 - ele2 for ele1, ele2 in zip(arr, arr2)]

[2 3 1 4]


[2, 3, 1, 4]

In [11]:
print(arr * arr2)

# Em pyton ppuro seria
[ele1 * ele2 for ele1, ele2 in zip(arr, arr2)]

[ 8 18  2 32]


[8, 18, 2, 32]

In [12]:
print(arr / arr2)

# Em pyton ppuro seria
[ele1 / ele2 for ele1, ele2 in zip(arr, arr2)]

[2. 2. 2. 2.]


[2.0, 2.0, 2.0, 2.0]

In [17]:
mat_identidade = np.identity(3)
mat_identidade
# ou
mat_identidade = np.eye(3)
mat_identidade

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
mat_quadrada = np.array([[1000, 200], [2, -7]])
inv_mat_quadrada = np.linalg.inv(mat_quadrada)
inv_mat_quadrada

array([[ 0.00094595,  0.02702703],
       [ 0.00027027, -0.13513514]])

In [19]:
mat_quadrada = mat

In [20]:
np.linalg.det(mat_quadrada)

-99432.00000000012

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print('*', arr1*arr2)

# 3 Formas de se obter o produto escalar
print('Dot', arr1.dot(arr2))

print('Matmul', np.matmul(arr1, arr2))

print('@', arr1 @ arr2)

* [1 4 9]
Dot 14
Matmul 14
@ 14


In [30]:
mat1 = np.array([[1000, 200], [2, -7]])
mat2 = np.array([[0, 1], [1, 0]])

print(mat1)
print(mat2)
print('-'*32)

dot = mat1.dot(mat2)
print('Dot')
print(dot)
print('-'*32)

matmult = np.matmul(mat1, mat2)
print('Matmult')
print(matmult)
print('-'*32)

at = mat1 @ mat2
print('@')
print(at)
print('-'*32)


[[1000  200]
 [   2   -7]]
[[0 1]
 [1 0]]
--------------------------------
Dot
[[ 200 1000]
 [  -7    2]]
--------------------------------
Matmult
[[ 200 1000]
 [  -7    2]]
--------------------------------
@
[[ 200 1000]
 [  -7    2]]
--------------------------------


In [35]:
mat1 = np.random.randint(0, 3, (3, 2))
mat2 = np.random.randint(0, 3, (2, 3))

print(mat1)
print(mat2)

#Erro 
#Erro no broadcast
# mat1 * mat2

dot = mat1.dot(mat2)
print('Dot')
print(dot)
print('-'*32)

matmult = np.matmul(mat1, mat2)
print('Matmult')
print(matmult)
print('-'*32)

at = mat1 @ mat2
print('@')
print(at)
print('-'*32)

print(f'''
mat1: {mat1.shape}
mat2: {mat2.shape}
dot: {dot.shape}
matmult: {matmult.shape}
@: {at.shape}
''')

[[2 0]
 [0 2]
 [2 0]]
[[2 1 2]
 [1 1 2]]
Dot
[[4 2 4]
 [2 2 4]
 [4 2 4]]
--------------------------------
Matmult
[[4 2 4]
 [2 2 4]
 [4 2 4]]
--------------------------------
@
[[4 2 4]
 [2 2 4]
 [4 2 4]]
--------------------------------

mat1: (3, 2)
mat2: (2, 3)
dot: (3, 3)
matmult: (3, 3)
@: (3, 3)



In [ ]:
array(
    mat1[0] @ mat2[0]
    mat1[1] @ mat2[1]
    mat1[2] @ mat2[2]
)

In [37]:
mat1 = np.random.random((2, 1))
mat2 = np.random.random((2, 1))

mat1 @ mat2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

In [43]:
x = np.linspace(0, 10)
print(x)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [ ]:
funcoes = [
    np.sin(x),
    np.cos(x),
    np.exp(x),
    np.log(x),
]